version: "3"

services:
  app:
    image: node:18
    container_name: web_app_container
    working_dir: /app
    volumes:
      - ./:/app   # 🔥 code mounted here
    ports:
      - "7200:3000"
    command: npm start

  mongo:
    image: mongo
    container_name: mongo_db_container
    ports:
      - "27018:27017"
