version: "3.8"

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "7200:3000"
    command: sh -c "npm install && npm start"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_db_jenkins
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
