apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: compassionconnect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: compassionconnect
  template:
    metadata:
      labels:
        app: compassionconnect
    spec:
      containers:
        - name: web
          image: alwazislam/compassionconnect:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-service:27017"
            - name: MONGODB_DB
              value: "disaster_db"
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"